# **_WEEK 5 HOMEWORK (NUMPY AND PANDAS)_**

### **Questions**

1. What does Pandas stand for?
2. What are the 2 collections used in Pandas?
3. Name 4 things Pandas can do for us.
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
5. What is a CSV?
6. When cleaning data what values do we not like in our data?

### _Answers_

1. Stands for either:
    * _Panel Data_
    * _Python Data Analysis_
2. The two collections are:
    * _NumPy_
    * _DataFrames_
3. 4 Things Pandas can do for us:
   1. Data Cleansing
   2. Data normalization
   3. Data visualization
   4. Data inspection
4. ???
5. Comma Separated Values file
6. Null values

In [21]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). 
#    You can use the reshape method -- `.reshape()`

import numpy as np

# Originally did arr = arange(1,13) to create my array but I could not get #12 to work correctly without creating the array like this... (see question 12 for more details) 
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
rarr = arr.reshape(2,3,2)
print(rarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
# 8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20.

lint = np.linspace(0,20, num=6)
print(lint)

[ 0.  4.  8. 12. 16. 20.]


In [19]:
# 9. Make a Deep Copy of the above array
import copy

lintball = copy.deepcopy(lint)
print(lintball)

[ 0.  4.  8. 12. 16. 20.]


In [18]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...
# ([[25, 16]])
# ([[11, 2], [13, 4]])
# ([[7, 81], [5, 6], [11, 12]])

a = ([[25, 16]])
b = ([[11, 2], [13, 4]])
c = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((a,b,c))

print("Array a is... ", a)
print("Array b is... ", b)
print("Array c is... ", c)
print("\nnewArray is... ", "\n", newArray)


Array a is...  [[25, 16]]
Array b is...  [[11, 2], [13, 4]]
Array c is...  [[7, 81], [5, 6], [11, 12]]

newArray is...  
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [17]:
# 11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("The Sorted Array now looks like this: ", "\n", sortedArray)

The Sorted Array now looks like this:  
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [22]:
# 12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

# I tried this with the reshaped array from #7 (im assuming this is the reshaped array it is asking for) but it would not work since the reshaped array has a shape of (2,3,2)
# so I made the original array into a 4x3 shape so that I could assign 4 variables to the array. I am not sure if the question is worded incorrectly or maybe 
# I was just missing something, I am not sure. 

v1,v2,v3,v4 = arr
print(v1)
print(v2)
print(v3)
print(v4)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [30]:
# 13. Combine and sort the following arrays into one called 'comboArray' ...
# one = ([10, 11, 12, 13, 14, 15, 16, 17])
# two = ([20, 21, 22, 23, 24, 25, 26, 27])
# three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))
print(comboArray)


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [40]:
# 14. Take 'comboArray' and perform the following slicing activities:
#     - print sec1 - the 2nd element
#     - print sec2 - all elements from the 3rd element to the last
#     - print sec3 - all elements from the 4th to the 14th elements
#     - print sec4 - the last 6 elements
#     - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
#     - print sec6 - from #20 every even element to the end
#     - print sec7 - from the last element moving forward, every 5th element.

print(comboArray[1]) #sec1
print(comboArray[2:]) #sec2
print(comboArray[3:14]) #sec3
print(comboArray[-6:]) #sec4
print(comboArray[-24:-10]) #sec5
print(comboArray[-8::2]) #sec6
print(comboArray[::-5]) #sec7


1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [ ]:
# 15. Using `Series`, create a `DataFrame` that looks like this:
# | Ingredients | Quantity | Unit |
#     |----|----|----|
#     | Flour | 4 | cups |
#     | Milk | 1 | cup |
#     | Eggs | 2 | large |
#     | Spam | 1 | can |


In [ ]:
# 16. Take this data and create a DataFrame named studentData
# {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#             'Height': [5.1, 6.2, 5.1, 5.2],
#             'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#             'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#             'Age': [21, 23, 24, 21],
#             'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#             'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
#         }

